DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE PRODUTO (
IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , VALOR_EURO  NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

/*
QUESTÃO:
1. QUANDO UM PRODUTO FOR INCLUÍDO OU ALTERADO O VALOR DO PRODUTO 
EM DÓLAR E EURO DEVE SER CALCULADO

Valor para conversão 1 Real = 3,9005 Dólar
Valor para conversão 1 Real = 4,3684 Euro
*/


-- TRIGGER INSERT ---


DELIMITER $$
CREATE TRIGGER TR_CONVERSAO_BI BEFORE INSERT ON PRODUTO FOR EACH ROW
BEGIN

	IF (
		NEW.VALOR_DOLAR IS NOT NULL AND NEW.VALOR_EURO IS NOT NULL
		OR NEW.VALOR_EURO IS NOT NULL AND NEW.VALOR_REAL IS NOT NULL
		OR NEW.VALOR_REAL IS NOT NULL AND NEW.VALOR_DOLAR IS NOT NULL
		) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'INFORME SÓ UM VALOR';
        
	ELSEIF (NEW.VALOR_DOLAR IS NULL AND NEW.VALOR_EURO IS NULL AND NEW.VALOR_REAL IS NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NENHUM VALOR INFORMADO';
        
	ELSEIF NEW.VALOR_REAL IS NOT NULL THEN
		SET NEW.VALOR_EURO = NEW.VALOR_REAL / 4.67;
        SET NEW.VALOR_DOLAR = NEW.VALOR_REAL / 4.22;
        
	ELSEIF NEW.VALOR_EURO IS NOT NULL THEN
		SET NEW.VALOR_REAL = NEW.VALOR_EURO *4.67;
        SET NEW.VALOR_DOLAR = NEW.VALOR_REAL / 4.22;
        
	ELSEIF NEW.VALOR_DOLAR IS NOT NULL THEN 
		SET NEW.VALOR_REAL = NEW.VALOR_DOLAR * 4.22;
        SET NEW.VALOR_EURO = NEW.VALOR_REAL /4.67;
            
	END IF;
    
END $$
DELIMITER ;



-- TRIGGER UPDATE-- 

DELIMITER $$
CREATE TRIGGER TR_CONVERSAO_BU BEFORE UPDATE ON PRODUTO FOR EACH ROW
BEGIN
	IF(NEW.VALOR_DOLAR IS NOT NULL AND NEW.VALOR_EURO IS NOT NULL
		OR NEW.VALOR_EURO IS NOT NULL AND NEW.VALOR_REAL IS NOT NULL
		OR NEW.VALOR_REAL IS NOT NULL AND NEW.VALOR_DOLAR IS NOT NULL
		) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'INFORME SÓ UM VALOR';
	ELSEIF (NEW.VALOR_DOLAR IS NULL OR NEW.VALOR_EURO IS NULL OR NEW.VALOR_REAL IS NULL) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'VALOR NÃO INFORMADO PARA UPDATE';
	ELSEIF (OLD.VALOR_REAL <> NEW.VALOR_REAL) THEN
		SET NEW.VALOR_DOLAR = NEW.VALOR_REAL / 4.22;
        SET NEW.VALOR_EURO = NEW.VALOR_REAL /4.67;
	ELSEIF (OLD.VALOR_DOLAR <> NEW.VALOR_DOLAR) THEN
		SET NEW.VALOR_REAL = NEW.VALOR_DOLAR * 4.22;
        SET NEW.VALOR_EURO = NEW.VALOR_REAL /4.67;
	ELSEIF (OLD.VALOR_EURO <> NEW.VALOR_EURO) THEN
		SET NEW.VALOR_REAL = NEW.VALOR_EURO *4.67;
        SET NEW.VALOR_DOLAR = NEW.VALOR_REAL / 4.22;
	END IF;
    
END $$
DELIMITER ;


-- SELECTS --


SELECT * FROM PRODUTO;
INSERT INTO PRODUTO (NOME, VALOR_REAL) VALUES ('ARROZ', 15);
INSERT INTO PRODUTO (NOME, VALOR_DOLAR) VALUES ('FEIJÃO',2.5);
INSERT INTO PRODUTO (NOME,VALOR_EURO) VALUES ('BATATA', 1.6);
INSERT INTO PRODUTO (NOME, VALOR_REAL) VALUES ('MACARRÃO', 21.5);
INSERT INTO PRODUTO (NOME, VALOR_REAL) VALUES ('CARNE', 45.9);
UPDATE PRODUTO SET VALOR_REAL = 25.9 WHERE IDPRODUTO = 1;
UPDATE PRODUTO SET VALOR_DOLAR = 3.6 WHERE IDPRODUTO = 2;
UPDATE PRODUTO SET VALOR_EURO = 2.9 WHERE IDPRODUTO = 3;
UPDATE PRODUTO SET VALOR_DOLAR = 2.6, VALOR_DOLAR = 1 WHERE IDPRODUTO = 4;
UPDATE PRODUTO SET VALOR_REAL = NULL WHERE IDPRODUTO = 5;
SELECT * FROM PRODUTO;
